language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build || true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
# language: node_js
# node_js:
#   - node
# cache:
#   directories:
#     - node_modules
# sudo: required
# services: docker
# script:
#   - npm run test

